pipeline {  
    agent{
        docker{
            image 'python:2.7-slim'
            args '--user root'
        }
    }
    stages{      
        stage("build"){  
            when{
                changeset "**/vote/**"
            }        
            steps{              
                echo 'Compiling worker app'              
                dir('vote'){                
                    sh 'pip install -i requirements.txt'              
                }          
            }      
        }      
        stage("test"){  
            when{
                changeset "**/vote/**"
            }  
            steps{              
                echo 'Running Unit Tets on worker app'  
                dir('vote'){                
                    sh 'nosetests -v'              
                }          
            }      
        }     
    }  
    post{    
        always{  
            echo 'Building multibranch pipeline for worker is completed..'
        }
        failure{
            slackSend (channel: "instavote-cd", message: "Build Failed - ${env.JOB_NAME}  ${env.BUILD_NUMBER} by ${BUILD_USER}\n More info at: ${env.BUILD_URL}")
        }  
        success{
            slackSend (channel: "instavote-cd", message: "Build Succeeded - ${env.JOB_NAME}  ${env.BUILD_NUMBER} by ${BUILD_USER}\n More info at: ${env.BUILD_URL}")
        }  
    }
}